# Generated by Django 2.2.3 on 2019-07-12 06:23

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('unmask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='compuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='compuser',
            name='address',
            field=models.TextField(default='hai'),
        ),
        migrations.AddField(
            model_name='compuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='compuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='compuser',
            name='first_name',
            field=models.CharField(default='hai', max_length=200),
        ),
        migrations.AddField(
            model_name='compuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='compuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='compuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='compuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='compuser',
            name='last_name',
            field=models.CharField(default='hai', max_length=200),
        ),
        migrations.AddField(
            model_name='compuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='compuser',
            name='username',
            field=models.CharField(default='hai', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='compuser',
            name='identity_card_no',
            field=models.CharField(default='hai', max_length=200),
        ),
        migrations.AlterField(
            model_name='compuser',
            name='identity_card_type',
            field=models.CharField(default='hai', max_length=200),
        ),
    ]
