# Generated by Django 2.2.3 on 2019-07-12 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unmask', '0002_auto_20190712_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_to',
            field=models.CharField(default='ismailshibiliya@gmail.com', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmask', to=settings.AUTH_USER_MODEL),
        ),
    ]
