# Generated by Django 2.2.3 on 2019-07-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unmask', '0003_auto_20190712_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compuser',
            name='email',
            field=models.CharField(default='ismailshibiliya@gmail.com', max_length=200),
        ),
    ]
